In [1]:
import numpy as np

In [2]:
# numpy의 검색 기능
# 이 코드는 안된다.

np.lookfor('array')

TypeError: 'NoneType' object is not iterable

In [3]:
# 앞에 *를 넣어주니까 된다.

np.lookfor('* array')

Search results for '* array'
----------------------------
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.modf
    Return the fractional and integral parts of an array, element-wise.
numpy.rint
    Round elements of the array to the nearest integer.
numpy.sqrt
    Return the non-negative square-root of an array, element-wise.
numpy.expm1
    Calculate ``exp(x) - 1`` for all elements in the array.
numpy.isnan
    Test element-wise for NaN and return result as a boolean array.
numpy.isnat
    Test element-wise for NaT (not a time) and return result as a boolean array.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, ele

In [8]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# reshape은 모양을 바꿔준다.
# numpy는 메모리에 저장될때 한줄로 저장되고 stride 개념에 따라서 행렬로 사용자에게 보여준다.
# reshape는 stride를 바꿔주므로 쉽게 모양 바꾸는게 가능하다.

a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a = np.arange(27)

In [13]:
a.shape

(27,)

In [14]:
a.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [15]:
# element 갯수가 reshape할 갯수와 안 맞을 경우에는 Error가 난다.

a.reshape(4,5)

ValueError: cannot reshape array of size 27 into shape (4,5)

In [16]:
# reshape은 자기자신을 바꾸지 않는 메서드이기 때문에 재사용할려면 재할당해줘야한다.

b = a.reshape(3,9)

In [17]:
# 재할당한 b의 0을 100으로 바꾸었다.

b[0][0] = 100
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [18]:
# a도 element가 바뀌었다?!
# 골때림
# reshape은 자기자신을 바꾸지 않는 mutable function이다. 그런데 값을 바꾸면 원본도 바뀐다.
# 그래서 .copy를 하고 사용하는 습관이 있어야한다.

a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

In [19]:
# -1은 numpy가 알아서 element 갯수에 맞춰서 모양 만들어준다.

a.reshape(3, -1)

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [20]:
# 행에 넣어도 된다.

a.reshape(-1, 9)

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [21]:
# 꼭 -1이 아니어도 된다.
# -(마이너스)만 붙으면 알아서 바꿔준다.

a.reshape(3, -100)

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [22]:
# reshape과의 차이점: 자기 자신을 바꿈.
# 상황에 맞춰서 reshape과 resize를 선택해서 사용하면 된다.
# 대부분의 교재에서는 reshape을 알려주는 편이다.

a.resize((3,9))

In [23]:
a

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [25]:
a = np.arange(27)

In [26]:
# element 갯수에 안 맞게 resize 시키면?
# 에러 안나네

a.resize((3,5))

In [27]:
# 갯수 맞춰서 잘라버렸다.

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
a = np.arange(27)

In [29]:
# element 갯수보다 많게 하면?
# 

a.resize((3,10))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [31]:
# reshape과 다르게 -(마이너스)를 써서 알아서 모양 맞추기는 못한다.

a.resize((-1, 10))

ValueError: negative dimensions not allowed

In [88]:
a = np.arange(27).reshape(3,9)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [33]:
# split 메서드: ndarray를 쪼개준다.
# 다음 코드는 자르는 기준이 없어서 에러 발생

np.split(a)

TypeError: split() missing 1 required positional argument: 'indices_or_sections'

In [36]:
# 자르는 기준: 1  =>  총 1개로 짤라라.

np.split(a, 1)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [37]:
# 2개로 자르고 싶으면 어떻게 하나요?
# 2가 에러났어요!

np.split(a, 2)

ValueError: array split does not result in an equal division

In [64]:
# tuple로 전달해줘야한다

np.split(a, (2,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [38]:
# 튜플에 숫자를 더 넣으면?
# 0에서 1까지 , 1에서 2까지, 2에서 끝까지 로 잘랐음.

np.split(a, (1,2))

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [39]:
# 0에서 2까지, 2에서 끝까지 잘랐음.
# array가 3개가 나왔지만, 2번째 애는 비어있음.

np.split(a, (2,2))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [40]:
# axis 개념을 추가해서 split 할 수도 있다.

np.split(a, (2,2), axis=1)

[array([[ 0,  1],
        [ 9, 10],
        [18, 19]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 2,  3,  4,  5,  6,  7,  8],
        [11, 12, 13, 14, 15, 16, 17],
        [20, 21, 22, 23, 24, 25, 26]])]

In [41]:
# horizontal split
# split(axis=1)과 동일하다.
# 한줄이라도 더 짧게 코딩할 수 있다.
# indices_or_sections 파라미터에 인자를 tuple로 넘겨줘야한다.

# 아래 코드는 int로 전달해서 Error

np.hsplit(a,5)

ValueError: array split does not result in an equal division

In [43]:
# tuple로 전달해서 실행됨.

np.hsplit(a,(5,))

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [44]:
# hsplit이 있으면?  vsplit도 있다.
# vertical split
# split(axis=0) 과 같다.

np.vsplit(a, (2,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [ ]:
b = np.arange(5)
c = np.arange(5,10)

In [47]:
# stack = split의 반대 개념

np.stack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
# axis 파라미터를 추가해서 모양을 다르게 합칠 수도 있다.

np.stack((b,c) , axis=1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [45]:
# stack(axis=0)과 같다.
# 세로로 붙일때 stack 대신 쓸 수 잇음. 

np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
# vstack이 있으면 반대개념 hstack도 있다.
# 얘는 stack(axis=1)과는 다르다. (조심)

np.hstack((b,c))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# numpy의 _붙은 삼총사  =>  c_, r_, s_
# 헷갈리기 쉬워서 잘 안알려준다.
# 이 삼총사가 생긴 이유 => matlab을 베껴서 만들다 보니 생김. 원래 matlab 코드

# np.hstack을 해주는 또다른 녀석이 r_이다.

np.r_[b,c]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# c_ -> ndarray를 합치는 방법 중 하나
# np.stack(axis=1)과 같음.

np.c_[b,c]

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [51]:
# .s_  =  slice 객체를 만들어 준다.
# slice 객체란? 아래에서 설명

np.s_[b,c]

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [53]:
# slice 객체
# slice를 하기 위해서 만들어진 애.

[1,2,3,4,5][slice(1,5)]

[2, 3, 4, 5]

In [54]:
# 위의 slice 객체가 하는 역할은 다음과 같다.

[1,2,3,4,5][1:5]

[2, 3, 4, 5]

In [55]:
# numpy에서 slice 객체이다.

np.arange(10)[np.s_[1]]

1

In [56]:
# np.stack(axis=1)과 같다.

np.column_stack([b,c])

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [58]:
# np.neaxis = 차원을 추가하는 역할
# 자세히 보면 []가 하나 더 생겼음을 알 수 있다.

a[np.newaxis]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]])

In [59]:
# 차원이 늘었다.

a[np.newaxis].ndim

3

In [61]:
# 원래는 새로운 차원을 추가하는 개념을 None으로 썼다.
# 그런데 사람들이 자꾸 헷갈려해서 np.newaxis라고 객체를 새로 만들었다.
# 사실은 None이랑 같은데 이름만 붙였다.

np.newaxis is None

True

In [62]:
# 그래서 그냥 None을 써도 된다.

a[None]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]])

In [70]:
# 이렇게 쓸 수 있다.
# 차원을 어디에서 확장 시켜 줄 것인가?

a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26]]])

In [121]:
a = np.arange(5)

In [122]:
# 차원을 늘려주는 메서드
# 어떤 axis를 기준으로 차원을 늘릴 것인지 정할 수 있다.

np.expand_dims(a, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [124]:
a = np.arange(27).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [127]:
# axis=0을 기준으로 차원을 늘림

np.expand_dims(a, 0)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]])

In [125]:
# axis=1을 기준으로 차원을 늘림

np.expand_dims(a, 1)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8]],

       [[ 9, 10, 11, 12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23, 24, 25, 26]]])

In [126]:
# axis=2을 기준으로 차원을 늘림

np.expand_dims(a, 2)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26]]])

In [146]:
a = np.arange(27).reshape(3, -1)
a = np.expand_dims(a, 0)
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]])

In [150]:
# 차원을 서로 바꿀 수 있다.
# 0과 2를 서로 바꾸는 개념

np.swapaxes(a, 0, 2)

array([[[ 0],
        [ 9],
        [18]],

       [[ 1],
        [10],
        [19]],

       [[ 2],
        [11],
        [20]],

       [[ 3],
        [12],
        [21]],

       [[ 4],
        [13],
        [22]],

       [[ 5],
        [14],
        [23]],

       [[ 6],
        [15],
        [24]],

       [[ 7],
        [16],
        [25]],

       [[ 8],
        [17],
        [26]]])

In [152]:
# 차원을 옮길 수 있다.
# 0을 2로 보내는 개념.

np.moveaxis(a, 0, 2)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26]]])

In [113]:
a = np.arange(40)

In [114]:
b = a.reshape(4, -1)

In [117]:
# split 할때 -(마이너스)를 쓰면 0으로 인식한다.

np.split(b, (-2, 2))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([], shape=(0, 10), dtype=int32),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])]

In [118]:
# 0을 넣었을 때랑 똑같이 잘라준다.
# 그런데... blank(빈 array)가 생기는 위치가 조금 다르다.
# 얘은 0에서 0, 0에서 2, 2에서 끝까지라는 개념.

# 위에서는 -2에서 2까지(-2,-1은 무시되고 0부터), 0에서 2까지(이미 뽑았으니 blank), 2에서 끝까지 인듯(?)
#    =>  -(마이너스)를 쓰면 골치아프니 쓰지 않는게 좋다고 하심.

np.split(b, (0, 2))

[array([], shape=(0, 10), dtype=int32),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])]

In [129]:
# structured arrays
# column 별로 column 이름과, 데이터 타입을 정할 수 있다.

# structured arrays는 "DB처럼 사용할 수 있다."  =>  얘를 기반으로 pandas가 탄생했다.

x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [130]:
# structured arrays는 python의 named tuple과 유사하다.

from collections import namedtuple

In [131]:
?namedtuple

In [132]:
# namedtuple을 사용하는 방법
# type으로 class 정의 안하고 class 만드는 방법과 비슷함.
# DB처럼 사용하고 싶을때 사용한다.

# tuple은 DB에서 row개념과 유사하다. (?) 무슨말이죵?..

Address = namedtuple('Adress', ('name', 'age', 'weight'))

In [133]:
# class 인스턴스 만드는 방법이랑 비슷하다.

a1 = Address('Rex', 27, 81.0)

In [134]:
# 인스턴스에서 attribute 접근하는 방식처럼 tuple을 쓸 수 있다.

a1.name

'Rex'

In [135]:
# type 이 type이다  :  class이다.

type(Address)

type

In [136]:
# namedtuple은 tuple이기 때문에 인덱싱할 수 있다.

a1[0]

'Rex'

In [137]:
# tuple이니까 key 방식으로는 못 쓴다.
# 헷갈리기 쉬움!

a1["name"]

TypeError: tuple indices must be integers or slices, not str

In [138]:
# 다시 numpy의 structure arrays로 돌아와봅시다.

x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [140]:
# 행(row)으로 접근 가능하다.

x[1]

('Fido', 3, 27.)

In [139]:
# key 방식으로 열(column)로 접근도 가능하다.
# namedtuple과 다르게 key 방식을 쓸 수 있다.

x["name"]

array(['Rex', 'Fido'], dtype='<U10')

In [141]:
# 단, namedtuple과 다르게 attribute 방식으로는 접근할 수 없음.

x.name

AttributeError: 'numpy.ndarray' object has no attribute 'name'

In [144]:
# dir에 컬럼 이름 자체가 없다.

'name' in dir(x)

False

In [153]:
# structured arrays는 stride 개념을 쓰기 때문에 값에 접근하는 속도가 엄청나게 빠르다.

In [159]:
# 연습용 데이터를 불러와보자.
# pandas가 설치 안되어 있으면 모양이 좀 다르게 보일 수도 있음.
# structured array가 어떻게 사용되는지 보자.

import seaborn as sns
tips = sns.load_dataset('tips')

# head는 상위 5개만 보여주는 메서드임. 
# 필기 가독성을 위해서 사용하겟음.
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [160]:
# structured arrays 기반으로 만들었기때문에, key 방식으로 쓸 수 있다.

tips['smoker'].head()

0    No
1    No
2    No
3    No
4    No
Name: smoker, dtype: category
Categories (2, object): [Yes, No]

In [164]:
# structured array 기반으로 만들었지만, attribute 방식으로도 불러올 수 있다.

tips.tip.head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [161]:
# size라는 column만 뽑고 싶은데, size를 치면 이상한 숫자가 튀어나온다.
# 여기서 size는 np.size이다. 
# numpy를 기반으로 만들었기 땜에 numpy의 size 메소드가 실행된 것이다.
# numpy에 있는 메소드명과 컬럼이름이 겹칠때는 attribute 방식으로 불러올 수 없다.(판다스)
# 이름이 겹칠때는 column 이름을 바꿔주는게 좋다. (관례상 뒤에 _를 붙임. ex: size_)

tips.size

1708

In [162]:
# shaple의 값을 서로 곱해주면 size이다.

tips.shape

(244, 7)

In [ ]:
# numpy의 structured arrays는 column 이름을 문자열만 쓸 수 있다.
# structured arrays의 column 이름은 숫자를 쓸 수 없다.

# pandas는 column 이름을 숫자로도 쓸 수 있다. (더 편리)
# 단, 이름이 숫자로 되면 attribute 방식으로 접근할 수 없다. (ex. tips의 컬럼 이름이 0일때 tips.0으로 접근 불가)
# 또한, column이름에 공백이 있거나, 중간에 .(점)이 있어도 attribute 방식으로 접근할 수가 없다.
# 숫자, 공백, 점은 python이 column 이름인지 아닌지 알 수 없기 때문이다. -> key 방식으로 접근해야함.

In [168]:
# structured array에서는 indexing 방법을 쓰면 row를 뽑을 수 있엇다.
# pandas는 error 난다.

tips[0]

KeyError: 0

In [165]:
# 판다스에서 행(row)을 불러오기 위해서는 loc를 이용해야한다.

tips.loc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [166]:
# loc와 iloc의 차이는 오후에 설명해줌.
# loc은 index의 이름을 기준으로 행을 뽑고, iloc는 index의 순서를 기준으로 행을 뽑음.
# pandas에서 index는 꼭 숫자가 아닐 수 있다.

tips.iloc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [ ]:
# pancy indexing 할 수 있다.

tips['tips', 'size', 'sex']

In [172]:
# pandas는 2차원 데이터 구조를 분석하기에 좋은 tool이다.
# 정형 데이터만 처리할 수 있다. (모양이 맞아야 한다.)

# 맨 왼쪽에 세로로 1,2,3.... 은 index라고 부른다.
# 맨 위에 가로로 total_bill, tip, sex...는 column name이라고 부른다. (또는 headers라고도 부른다.)

tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [174]:
# 한줄만 뽑으면 모양이 다르다.
# 이렇게 생긴 애들은 Series라고 부른다.
# 위에 처럼 보이는 애들은 DataFrame이라고 부른다.

tips.day.head()

0    Sun
1    Sun
2    Sun
3    Sun
4    Sun
Name: day, dtype: category
Categories (4, object): [Thur, Fri, Sat, Sun]

In [176]:
# Series를 .values를 하면 numpy 포맷으로 바꿔준다.

tips.day.values

[Sun, Sun, Sun, Sun, Sun, ..., Sat, Sat, Sat, Sat, Thur]
Length: 244
Categories (4, object): [Thur, Fri, Sat, Sun]

In [177]:
# numpy의 broadcasting 기법이 pandas에서도 된다.
# 모양 안 맞춰줘도 자동으로 계산해줌.

tips.tip + 5

0       6.01
1       6.66
2       8.50
3       8.31
4       8.61
5       9.71
6       7.00
7       8.12
8       6.96
9       8.23
10      6.71
11     10.00
12      6.57
13      8.00
14      8.02
15      8.92
16      6.67
17      8.71
18      8.50
19      8.35
20      9.08
21      7.75
22      7.23
23     12.58
24      8.18
25      7.34
26      7.00
27      7.00
28      9.30
29      8.00
       ...  
214    11.50
215     6.10
216     8.00
217     6.50
218     6.44
219     8.09
220     7.20
221     8.48
222     6.92
223     8.00
224     6.58
225     7.50
226     7.00
227     8.00
228     7.72
229     7.88
230     7.00
231     8.00
232     8.39
233     6.47
234     8.00
235     6.25
236     6.00
237     6.17
238     9.67
239    10.92
240     7.00
241     7.00
242     6.75
243     8.00
Name: tip, Length: 244, dtype: float64

In [181]:
# reduction  :  전체 값을 하나로 표현함.
# pandas에서도 reduction 쓸 수 있다.

print(tips.tip.sum())
print(tips.tip.mean())

731.5799999999999
2.9982786885245902


In [191]:
# pandas에서 행 뽑기
# loc과 iloc의 차이
# iloc는 index의 위치(숫자)를 기준으로함.

tips.iloc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [192]:
# loc는 index의 이름을 기준으로함

tips.loc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [193]:
# numpy처럼 slicing도 가능하다.

tips.iloc[0:6]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4

In [194]:
# 근데 loc에서 슬라이싱은 조금 다르다.
# 6까지 행을 가져왔다.
# 왜냐하면 loc은 이름을 기준으로 하기 때문에 "index이름이 0에서 6까지 인것"을 가져와라 는 뜻

tips.loc[0:6]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2

In [197]:
# iloc은 숫자를 기반으로 하기때문에 column도 숫자로 슬라이싱해올 수 있다.
# iloc은 column을 이름으로 하면 에러남.

tips.iloc[0:6, 1:3]

tip     sex
0  1.01  Female
1  1.66    Male
2  3.50    Male
3  3.31    Male
4  3.61  Female
5  4.71    Male

In [196]:
# loc은 이름을 기준으로 하기 때문에 column도 이름을 기준으로 슬라이싱할 수 있다.
# loc에 column을 숫자(순서)로 하면 에러남.

tips.loc[0:6, ['tip', 'sex']]

tip     sex
0  1.01  Female
1  1.66    Male
2  3.50    Male
3  3.31    Male
4  3.61  Female
5  4.71    Male
6  2.00    Male

In [201]:
# pandas에서 pancy indexing으로 가져올 수 있다.

tips[['tip', 'sex']].head()

tip     sex
0  1.01  Female
1  1.66    Male
2  3.50    Male
3  3.31    Male
4  3.61  Female

In [ ]:
# pandas에서 열(column)을 가져오는 방법 3가지
# 1. key 방식
# 2. attribute 방식
# 3. pancy indexing 방식   =>   pancy indexing은 특이하게 DataFrame으로만 가져온다.

In [210]:
tips["tip"].head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [211]:
tips.tip.head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [212]:
# pancy indexing만 DataFrame 형태이고, 나머지는 Series로 나온다.

tips[['tip']].head()

tip
0  1.01
1  1.66
2  3.50
3  3.31
4  3.61

In [207]:
# key방식이 제일 빠르다.
# 코드 치기는 귀찮게 생겼지만.... ㅋ
# numpy를 그대로 쓰기 때문에 제일 빠름.

%timeit tips["tip"].head()

55.3 µs ± 3.41 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [208]:
%timeit tips.tip.head()

58.2 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [213]:
# 제일 느리다.

%timeit tips[['tip']].head()

934 µs ± 16 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [214]:
# 숫자로만 하는 iloc가 더 빠르다.

%timeit tips.iloc[0]

414 µs ± 19.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [215]:
# loc보다 느리다.

%timeit tips.loc[0]

438 µs ± 9.75 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [216]:
# pandas에서 row 뽑는 방법 4가지. 
# 1. loc
# 2. iloc
# 3. at (pandas에만 있는 기능임)
# 4. iat (pandas에만 있는 기능임)

In [223]:
# 이름으로 특정 행/열의 값 뽑기

tips.at[0,'tip']

1.01

In [221]:
# 숫자로 특정 행/열의 값 뽑기

tips.iat[0,1]

1.01