# Numpy
- 쓰는 이유
    1. 속도가 빠르다.
    2. 사용하기 쉽고 편하다.


- 속도가 빠른 이유
    - C로 만들어졌기 때문이다.
    
    
- numpy를 기반으로 pandas, scikit, tensorflow, pytorch 만들었다.
    - numpy는 low level이기 때문에 high level(pandas 등)을 쓰면 굳이 알 필요가 없긴 하다.
    - 그러나 이 분야를  깊게 배우고 잘 사용하려면 low level을 알아야한다.
    - 최근에는 numpy만으로 구현하는 책들이 유행하고 있다.


- vectorization(벡터화)
    - 행렬의 장점: 한번에 여러가지 연산을 계산할 수 있다.
    - for문 없이 연산하는 녀석들(이터레이터, 제너레이터, map/filter/reduce, 컴프리헨션) 이 빠른 이유와 비슷함.
    

- GPU를 지원하지 않는다.
    - 그래서 tensorflow와 pytorch는 GPU를 지원하는 tensor라는 구조를 만들었다.

- 어떤 현상을 벡터화시키는 것이 핵심이다.
    - 흑백 이미지: 2차원으로 표현 가능
    - 컬러 이미지: 3차원으로 표현 가능(r,g,b 채널)
    - 흑백 동영상: 3차원으로 표현 가능 (흑백이미지를 시간에 따라서 나열하면 됨)
    - 컬러 동영상: 4차원으로 표현 가능

---

## 개념

In [1]:
import numpy as np

In [2]:
# __dir__과 dir()의 차이점 : dir()은 정렬되서 나온다.
# 대문자 부터 나오는 이유: ascii 코드 순서대로... A는 65, a는 97....

# 중간중간 보면 수학 함수 용어 많이 보임

dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [ ]:
# factory method
# 디자인 패턴 중 하나
# 인스턴스화 하지 않고 인스턴스로 사용하는 방법.
# 인스턴스를 만드는 방법 3가지: 클래스를 인스턴스화, 리터럴 방식, factory method

# import array 하면 파이썬 공식적으로 array라는게 있다.
# 그런데 파이썬 공식 array는 안쓴다.

# np.array는 호모지니어스이다.
# 호모지니어스는 데이터 타입 체크를 할 필요가 없기 때문에 속도가 빠르다.

np.array

In [8]:
# array 타입을 만들자. 
# int 들어감.
# array라고 앞에 붙어있음.  ->  앞으로 라이브러리 쓰다가 array라고 붙은 애들은 다 numpy로 만들어서 그렇다 생각하믄 됨.

a = np.array(1)
a

array(1)

In [6]:
# 리스트를 넣을 수도 있다.

a = np.array([1,2])
a

array([1, 2])

In [7]:
# 튜플을 집어넣었는데 리스트로 바뀌었다.
# mutable 타입이구나!
# mutable이면 골치아픈 일이 생길 수 있따... deep copy, swallow copy 개념 알아야함.

a = np.array((1,2))
a

array([1, 2])

In [9]:
# 원래 이름은 ndarray
# ndarray : n차원 array이다.

type(a)

numpy.ndarray

In [11]:
# 공백이 있으면 차원이 나뉘어짐을 알 수 있다.
# 다차원을 읽기 편하게 보여주는 것이지....

a = np.array([[[1,2], [3,4]], [[1,2], [3,4]]])
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [16]:
# dtype이라는게 생겼다.
# 호모지니어스인데 data type이 왜 필요할까?

n = np.ndarray(0)
n

array([], dtype=float64)

In [17]:
# type은 똑같다.

type(n)

numpy.ndarray

In [23]:
# 얘는 클래스
print(type(np.ndarray))

# 얘는 factory method
print(type(np.array))

<class 'type'>
<class 'builtin_function_or_method'>


In [14]:
# 아까의 np.array는 호모지니어스라고 했다.
# 그런데 int와 str을 섞었는데 된다?  =>  dtype이 '<U1'이 되었다. 유니코드라는 뜻이다.
# 결과를 잘 보면 '1', '2', '3'으로 바뀌었다.  =>  '1'에 맞춰서 나머지도 같은 타입으로 바뀌었다. -> 호모지니어스
# 팩토리 메서드라서...가능...?

n = np.array(['1',2,3])
n

array(['1', '2', '3'], dtype='<U1')

In [60]:
# np.ndarray는 int가 아니면 에러를 내버린다.

np.ndarray(['1',2,3])

TypeError: 'str' object cannot be interpreted as an integer

In [57]:
# dtype을 지정해도 안된다.

np.ndarray(['1',2,3], dtype="<U1")

TypeError: 'str' object cannot be interpreted as an integer

In [58]:
# type을 통일시켜도 문자열 자체가 안된다.

np.ndarray(['1','2','3'])

TypeError: 'str' object cannot be interpreted as an integer

In [59]:
# 다 안된다~
# ndarray 객체 만들때는 np.array / np.ones / np.zeros / np.empty 등을 쓰자~

np.ndarray(['1','2','3'], dtype="<U1")

TypeError: 'str' object cannot be interpreted as an integer

In [25]:
# dir로 살펴보자.

n = np.array(['1',2,3])
dir(n)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [26]:
# vars는 인스턴스가 가지고 있는 값을 보여준다.
# 값을 한개만 가지는 애다.
# 값을 한개만 기지는 vars가 안 된다.

vars(n)

TypeError: vars() argument must have __dict__ attribute

In [49]:
a = np.array([[1,2],[3,4]])

In [28]:
# 몇차원인지 알려주는 어트리뷰트

a.ndim

2

In [29]:
# len을 쓸 수도 있따. 

len(a)

2

In [30]:
# 행렬의 구조를 알려주는 어트리뷰트
# 행렬 계산을 하려면 행과 열의 구조가 맞아야하므로 중요하다.

a.shape

(2, 2)

In [31]:
# C 방식으로 저장했는지, 포트란 방식으로 저장했는지 알 수 있다.
# C 방식은 1,2,3,4로 저장하고, 포트란은 1,3,2,4로 저장한다.
# C는 가로, 포트란은 세로.

a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [32]:
# 원소의 갯수를 알려줌.
# 1,2,3,4 니까 4개

a.size

4

In [33]:
# 각각의 원소가 몇 비트인가? 알려줌.
# 얘는 4비트네.

a.itemsize

4

In [34]:
# data type을 알려줌.
# itemsize와 밀접한 연관이 있음.
# itemsize*8=dtype

a.dtype

dtype('int32')

In [50]:
# numpy는 행렬을 1렬로 저장한다.  ->  속도가 빠른 이유.
#                              ->  파이썬 list는 ㅣinked list로서 원소의 메모리 주소만 일고 있으며, 필요할때 원소 주소를 찾아서 가져옴.
#                              ->  넘파이는 메모리 주소가 필요없이 메모리 상에서 연속적으로 (1줄로) 저장한다. 
#                              ->  호모지니어스이므로 타입 체크도 안함(=빠름)
# 보여줄때는 행렬로 보여준다.
# 1렬로 저장된 값을 일정한 길이로 잘라서 행렬로 보여준다.
# strides는 (일정한 길이, 비트크기) 
# (8, 4) ->  8비트마다 1개의 행으로 잘라서 보여주고, 1개 원소는 4비트이다.
#        -> 8비트마다 1개 행(row to row), 4비트마다 1개 열(column to column)

# 포트란 방식일 경우 strides의 순서가 반대일 것임(4,8)

# ppt의 그림으로 봐야 이해가 잘 됨.

a.strides

(8, 4)

In [39]:
# 파이썬에서는 리스트끼리 + 연산하면 그대로 이어붙여줬다.

x = [1,2,3,4]
y = [2,3,4,5]
x + y

[1, 2, 3, 4, 2, 3, 4, 5]

In [40]:
# numpy에서는 행렬처럼 각각의 행과 열을 더해준다.

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a + b

array([3, 5, 7, 9])

In [42]:
# 파이썬에서 이렇게 행렬 더하기 연산을 하려면 어렵게 해야한다. 다음같이.
# 그래서 numpy가 편하다고 하는 것이다!

[x+y for x,y in zip(x,y)]

[3, 5, 7, 9]

In [43]:
# 행렬 빼기도 할 수 있다.

a - b

array([-1, -1, -1, -1])

In [44]:
# 곱하기는 행렬 곱셈이 아니다.
# 같은 위치에 있는 원소끼리 곱해줬다. 
# element-wise 라고 한다.

a * b

array([ 2,  6, 12, 20])

In [46]:
a = np.array([[1,2],[3,4]])

# 행과 열을 반전시켜줌.
a.T

array([[1, 3],
       [2, 4]])

In [52]:
# dtype을 정할 수 있다.

np.array([[1,2],[3,4]], dtype="int64")

array([[1, 2],
       [3, 4]], dtype=int64)

In [51]:
# type code로 짧게 표현할 수도 있다.

np.array([[1,2],[3,4]], dtype="i8")

array([[1, 2],
       [3, 4]], dtype=int64)

In [55]:
# 사용할 수 있는 dtype 종류.
# 엄청 많다;;
# 하지만 우리는 빅데이터 과정.... 우리가 관심있는 애는 int64, float64뿐이다.

np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint32,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float64,
 'g': numpy.float64,
 13: numpy.float64,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,
 'c

In [53]:
# 32bit짜리를 설치했는지, 64bit짜리를 설치했는지에 따라서 다르게 나옴.
# 32비트로 설치했으면 152개 나오고, 64비트로 설치하면 더 나옴.

len(np.sctypeDict)

152

In [54]:
# 내가 뭘 설치했는지 보자.
# x86(32비트)를 설치했군.

np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/JINHYO/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/JINHYO/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/JINHYO/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C

In [ ]:
# axis

# ppt를 봐야할거 같다... 말로 설명 불가...

# axis=0  :  행끼리 계산
# axis=1  :  열끼리 계산

# shpae이 (10,3)일때,  
# axis=0으로 더하면  ->  결과는 3개
# axis=1으로 더하면  ->  결과는 10개

## 만들기

In [63]:
# 파이썬의 range같은 녀석

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# 모양을 바꿔준다.
# mutable의 메서드 결과 3가지 유형 : 자기자신을 바꾸고 none을 반환, return은 있지만 자기자신은 그대로, return도 있고 자기자신도 바뀜
# reshape은 자기자신을 바꾸지 않고 return만 있음.
# copy 개념

a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
# 자기자신은 안 바뀌었음.

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# 바꾼 결과를 저장하려면 재할당해줘야함.

a = a.reshape(2,5)

In [72]:
# 더하기!
# 모든 원소를 더해준다.

a.sum()

45

In [68]:
# sum에 axis를 지정할수가 있다.

?a.sum

In [69]:
# axis에 따라서 원소를 더해준다.

a.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [70]:
a.sum(axis=1)

array([10, 35])

In [71]:
# 평균(mean)도 axis를 지정할 수 있음.
# 시험성적 평균 내기 같은거에 유용함.

a.mean(axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [73]:
# 넘파이가 얼마나 빠른가 볼까나?

%time sum(range(1000000))

Wall time: 46 ms


499999500000

In [85]:
# 속도가 훨씬 빠르다;; 거의 5배;;

%time np.sum(np.arange(1000000, dtype='i8'))

Wall time: 7 ms


499999500000

In [86]:
# 참고
# dtype 기본이 int32라고 지금 되어 있어서 결과가 다르게 나옴.

%time np.sum(np.arange(1000000))

Wall time: 4 ms


1783293664

In [87]:
# 0으로 된 행렬 만들기.
# 인자로 shape을 준다.

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
# 1로만 된 행렬 만들기.

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [90]:
# 원하는 값으로만 된 행렬 만들기.

np.full((3,4), 3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [94]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
# like가 붙으면 인자로 들어오는 행렬과 같은 모양으로 만들어준다.
# 행렬 연산할때 모양(shape)이 맞아야 한다.
# 그래서 like를 자주 쓰게 된다.

np.zeros_like(a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
# 단위 행렬
# 옵션이 더 많다.

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
# 단위행렬
# 옵션이 eye보다 적어서 빨리 만들 수 있다.

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
# 하삼각 행렬 만들기. (lower triangle)
# 아무튼... 이렇게 이름 붙은 행렬은 다 만들 수 있다.

np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [101]:
# 상삼각 행렬

np.triu((3,3))

array([[3, 3],
       [0, 3]])

In [104]:
# 전치행렬

b = np.tri(3)
np.transpose(b)

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [108]:
# n등분 해준다.
# default는 50이다.

np.linspace(0, 99)

array([ 0.        ,  2.02040816,  4.04081633,  6.06122449,  8.08163265,
       10.10204082, 12.12244898, 14.14285714, 16.16326531, 18.18367347,
       20.20408163, 22.2244898 , 24.24489796, 26.26530612, 28.28571429,
       30.30612245, 32.32653061, 34.34693878, 36.36734694, 38.3877551 ,
       40.40816327, 42.42857143, 44.44897959, 46.46938776, 48.48979592,
       50.51020408, 52.53061224, 54.55102041, 56.57142857, 58.59183673,
       60.6122449 , 62.63265306, 64.65306122, 66.67346939, 68.69387755,
       70.71428571, 72.73469388, 74.75510204, 76.7755102 , 78.79591837,
       80.81632653, 82.83673469, 84.85714286, 86.87755102, 88.89795918,
       90.91836735, 92.93877551, 94.95918367, 96.97959184, 99.        ])

In [106]:
# 로그를 n등분 해준다.
# default는 50이다.

np.logspace(1,100)

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [109]:
# 아무 값이나 채워넣음.

np.empty((4,2))

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 2.21341409e-321],
       [1.42410974e-306, 1.02916796e-311]])

## 뽑아내기

In [140]:
a = np.arange(10).reshape((2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [141]:
# 인덱싱과 슬라이싱 가능함.
# 행을 뽑아옴.

a[1]

array([5, 6, 7, 8, 9])

In [142]:
# 행에서 슬라이싱 한번 더 할 수 있다. -> 열 뽑음

a[1][3]

8

In [143]:
# 컴마로 한번에 인덱싱할 수 있다.
# 파이썬에는 없고 넘파이에만 있는 기능
# 첫번째는 행, 두번째는 열

a[1,3]

8

In [144]:
# :는 처음부터 끝까지라는 뜻.
# 모든 행에서, 3번째 열만 가져오라는 뜻.

a[:,3]

array([3, 8])

In [146]:
# (시작):(끝)  ->  파이썬 list의 슬라이싱과 같음.

a[:, 2:4]

array([[2, 3],
       [7, 8]])

In [145]:
# :을 하나 더 쓰면  ->  ~마다.
# :2  ->  2개마다 가져옴.

a[:,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [119]:
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [122]:
a[:,2]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26]])

In [123]:
# ...은 전체라는 뜻으로 쓸 수 있다.

a[1,...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [125]:
a[:2, :, 1]

array([[ 1,  4,  7],
       [10, 13, 16]])

In [147]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
# 조건을 이용할 수도 있다.

a[a>3]

array([4, 5, 6, 7, 8, 9])

In [139]:
# 조건을 여러개 쓸 수도 있다. 

a[(a<3) | (a>7)]

array([0, 1, 2, 8, 9])

In [136]:
# 마스킹 기법을 쓸 수도 있따.
# True에 해당하는 값만 나오고, False는 안나온다.

a[[True,True,False,False,True,True,True,True,True,True,]]

array([0, 1, 4, 5, 6, 7, 8, 9])

In [154]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [155]:
# fancy indexing
# 행 뽑는 방법.
# 해당하는 행만 뽑아온다.
# 리스트로 전달한다.
# 리스트 안에 있는 숫자들은 다 행을 의미한다. (열x)

a[[1,3]]  # ->  두번째행과 네번째행 가져오기

array([[2, 3],
       [6, 7]])

In [160]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [164]:
# 행과 열을 지정해서 가져오기.
# zip처럼 행에서 값1개, 열에서 값1개 가져와서 인덱싱해온다.
# (1,2), (2,3), (4,4) 를 가져오는 것과 같다.

a[[1,2,4], [2,3,4]]

array([ 7, 13, 24])

---

# 연산하기

In [167]:
b = np.nditer(a)

In [171]:
# iter는 next가 짝궁이지!
# for 쓰면 vectorize 개념에 부합하지 않는것이다.

next(b)

array(3)

In [172]:
x = np.arange(5)
y = np.arange(5)

In [173]:
# element-wise로 계산함.
# 행렬곱이 아님.

x*3

array([ 0,  3,  6,  9, 12])

In [174]:
# broadcasting
# numpy가 이놈 덕분에 편하다.
# 행렬 연산인데 shape이 안 맞아도 계산해준다.
# 자동으로 크기를 맞춰준다.

x + 3

array([3, 4, 5, 6, 7])

# ufunc(Universal Function)
- python에 있는 함수는 대부분 있다고 생각하면 된다.
- 속도가 python보다 빠르다
- ndarray 안에 있는 데이터 원소 별로 연산을 수행하는 함수
- vectoriaze 시킨 것과 안 시킨거 다 적용시킬 수 있는 함수 (보편적'universal'으로 적용가능함)

In [175]:
# 숫자 관련해서 많은 함수가 있다.

np.abs(-1)

1

In [176]:
np.ceil([2.9, 1, 2, 3, 0.3])

array([3., 1., 2., 3., 1.])

In [178]:
?np.ceil

# etc

In [177]:
# numpy 자체에서 함수를 설명해주는 기능이 있다.
# shift + tab 해서 나오는 정보가 빈약하다 싶으면 numpy의 설명을 보면 자세하다.

np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

In [183]:
# iinfo는 numpy의 숫자형에 대한 설명

np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [184]:
b = np.arange(5,10)

In [185]:
# db할때 where는 조건이었다.
# where는 조건에 해당하는 index를 반환한다.

np.where(b>5)

(array([1, 2, 3, 4], dtype=int64),)

In [186]:
# where해서 index를 알아낸 다음에, fancy indexing에 활용할 수 있다.

b[np.where(b>5)]

array([6, 7, 8, 9])

In [187]:
# 최소값 찾기-1
# 얘는 함수

np.argmin(b)

0

In [188]:
# 최소값 찾기-2
# 얘는 메소드

b.argmin()

0

In [189]:
from numpy import pi

In [190]:
from math import pi as mpi

In [191]:
pi

3.141592653589793

In [192]:
mpi

3.141592653589793

In [193]:
# numpy의 pi와 python math의 pi와 똑같다.
# 똑같음에도 불구하고 만들어 놓은 이유는 -> import했을때 memory 관리에 효율적임.

pi == mpi

True

In [194]:
# ...은 슬라이싱할때 전체라는 뜻으로 썼었다.
# 얘는 원래 파이썬에 있는 애다.
# 그리고 행렬이 너무 클때 중간에 생략하는 뜻으로 ...이 사용되기도 한다.

type(...)

ellipsis

In [195]:
# 얘를 초기화도 할 수 있고 별거 다 할 수 있음
# 근데 ...은 안쓰는게 좋다. 실수 많이 함.

dir(...)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [196]:
# 아까 pi는 파이썬의 pi와 같았는데,
# numpy의 nan은 파이썬의 nan과 다르다.
# 얘는 외워야함...

np.nan == float('nan')

False

In [198]:
t = float('nan')
t

nan

In [200]:
np.set_printoptions(threshold=np.nan)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [199]:
np.set_printoptions(threshold=t)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [201]:
# 상수인 애를 이렇게 만들어놓음
# 이건 어쩔 수 없이 외워야한다...

np.newaxis is None

True

In [202]:
a = np.array([[1,2], [3,4]])
b = np.array([[2,1], [4,3]])

In [205]:
# element-wise
a * b

array([[ 2,  2],
       [12, 12]])

In [203]:
# 이 연산자는 numpy에서만 사용한다.
# numpy측에서 연산자가 부족하다고 파이썬 측에 요구해서 3.6부터 생김.
# numpy가 얼마나 파워가 쎈지 알 수 있는 사례.

# 행렬 곱

a @ b

array([[10,  7],
       [22, 15]])

In [204]:
# 또 다른 행렬 곱 계산.

a.dot(b)

array([[10,  7],
       [22, 15]])

In [206]:
a = np.arange(10).reshape(2,5)

In [207]:
b = a

In [208]:
a[0][0] = 100

In [209]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [210]:
# 얘는 카피가 아니라 그냥 할당했기 때문에 바뀌는게 맞다.

b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [211]:
c = b.copy()

In [212]:
b[0][0] = -100

In [213]:
b

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [214]:
# numpy의 copy는 기본적으로 deepcopy이다.
# python에서 copy하면 기본적으로 swallow copy인 것과 다르다.

c

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [215]:
# numpy에서는 swallow copy가 view()이다.

d = c.view()

In [217]:
d[0][0] = 50

In [218]:
d

array([[50,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [219]:
# swallow copy이므로 변한다.

c

array([[50,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

##### 공식 문서 quick start 보고 복습
- https://docs.scipy.org/doc/numpy/user/quickstart.html
- 스스로 학습하기

---

# scipy
- 과학에서 많이 사용하는 기능(함수)을 미리 만들어놓은 패키지

In [179]:
from scipy.special import factorial

In [180]:
factorial([3,4,5])

array([  6.,  24., 120.])

In [181]:
# scipy도 numpy를 기반으로 만들었기 때문에, np.info에서도 설명을 볼 수 있다.

np.info(factorial)

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


# 과제
- quickstart 안의 링크의 크로울링해서 정리해오기...
- 자기가 공부할 수 있게 정리하는 목적..?인척? ㅋ

In [231]:
import sqlite3
import requests
from bs4 import BeautifulSoup

In [242]:
url = "https://docs.scipy.org/doc/numpy/user/quickstart.html"
headers= {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"}
resp = requests.request('get', url, headers=headers)
dom = BeautifulSoup(resp.text, 'lxml')

In [243]:
dom.select('a.reference.internal')

[<a class="reference internal" href="../reference/generated/numpy.array.html#numpy.array" title="numpy.array"><code class="xref py py-obj docutils literal notranslate"><span class="pre">array</span></code></a>,
 <a class="reference internal" href="../reference/generated/numpy.zeros.html#numpy.zeros" title="numpy.zeros"><code class="xref py py-obj docutils literal notranslate"><span class="pre">zeros</span></code></a>,
 <a class="reference internal" href="../reference/generated/numpy.zeros_like.html#numpy.zeros_like" title="numpy.zeros_like"><code class="xref py py-obj docutils literal notranslate"><span class="pre">zeros_like</span></code></a>,
 <a class="reference internal" href="../reference/generated/numpy.ones.html#numpy.ones" title="numpy.ones"><code class="xref py py-obj docutils literal notranslate"><span class="pre">ones</span></code></a>,
 <a class="reference internal" href="../reference/generated/numpy.ones_like.html#numpy.ones_like" title="numpy.ones_like"><code class="xref 

In [246]:
con = sqlite3.connect("numpyReferences.db")

In [247]:
cur = con.cursor()

In [267]:
cur.executescript("""
DROP TABLE IF EXISTS table1;
CREATE TABLE table1(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    reference VARCHAR(30) NOT NULL,
    url TEXT NOT NULL);""")

In [268]:
con.commit()

In [269]:
len([_ for _ in dom.select('a.reference.internal') if _.has_attr("title")])

154

In [270]:
for tag in  [_ for _ in dom.select('a.reference.internal') if _.has_attr("title")]:
    ref = tag["title"]
    ref_url = requests.compat.urljoin(url, tag["href"])
    cur.execute("INSERT INTO table1(reference, url) VALUES(?, ?)", [ref, ref_url])
con.commit()

In [271]:
cur.executescript("""
DROP TABLE IF EXISTS table2;
CREATE TABLE table2(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    table1_id INTEGER NOT NULL,
    expression VARCHAR(30) NOT NULL,
    description TEXT NOT NULL);""")
con.commit()

In [294]:
cur.execute("SELECT id, url FROM table1")
for table1_id, url in cur.fetchall():
    resp = requests.request('get', url)
    dom = BeautifulSoup(resp.text, 'lxml')
    exp = dom.select("dl > dt")[0].text
    desc = dom.select_one("dl > dd > p").text
    cur.execute("INSERT INTO table2(table1_id, expression, description) VALUES(?, ?, ?)", [table1_id, exp, desc])
con.commit()