# NumPy/SciPy 개요

▶ 속도의 문제 해결 방법   
1. 좋은 컴퓨터 사용하기 (gpu나 분산컴퓨터를 사용해) → 금전적인 문제가 있음  
2. 파이썬의 언어의 단점을 보완하는 방법으로 파이썬을 컴파일 할 수 있다. (싸이썬)  
3. pypy 파이썬으로만 된 파이썬 (파이썬의 단점인 다이나믹타입, 스택 등을 최적화 시켜서 파이썬보다 5배 정도 빠르다. 문법수정 필요 없음)   
4. (글루 랭귀지 -> 다른언어랑 잘 붙는다.) 병목현상이 일어나는 부분을 c 코드로 짠다.  
5. 알고리즘을 이용한다.  

▶ 이중 계산 관련된 속도를 빠르게 하는 것이 NumPy이다.   

▶ NumPy ☆☆☆
1. 속도 빠르다  
2. 편하고 쉽다.  

<빠른 이유>
1. c로 만들어짐 
2. 데이터 구조가 데이터구조가 벡터화되어있다.  (효율적인 자료구조)  
3. 호모지니어스  
4. 일렬로 저장하고 strides로 표현하기 때문에   

<쉬운 이유>  
1. 데이터 타입을 지정하면 알아서 처리해준다. (파이썬 숫자형을 다 사용할 수 있음. 단, int를 더 쪼갠다.(longlong 등)  
2. 저장방식을 리를엔디언, 빅엔디언까지 지원해준다.  
(수집한 데이터를 numpy 데이터로 바꾸면 아주 효율적으로 사용할 수 있다.)  
3. broadcasting

▶ Vectorization (벡터화)  
for을 쓰지 않고 vector(array)를 써서 연산하는 것.

백터(array)라고 하는 것은 for 구문을 돌리지 않음. loop를 쓰면 속도가 느려짐 (이터/제너, 컴프리헨션, 맵/필터/리듀스)  
함수형 패러다임도 for을 거의 안씀. 백터화도 for을 쓰지 않고 연산을 하는데 for쓰면 연산의 효율성이 떨어진다.  

행렬 : 한번에 여러개의 수를 계산 할 수 있다. 
NumPy는 gpu를 지원하지 않음. 그래서 tensor을 만들음  

숫자가 크면 클 수록 빨라짐.
작은 범위에서는 array programing(vectorization)이 느릴 수 도 있다.

▶ array 
백터는 방향이 있음. 벡터(방향, 크기) 스칼라는 크기만   
1차원 벡터는 방향이 없다고 생각해라.     
2차원 매트릭스  -> 이미지   
3차원 패널데이터(tensor)  → ND Array   -> 3차원(2차원 데이터를 시간순으로 만드는 것)   
...n차원 tensor

★ 어떤 형상을 벡터화 시키는 게 핵심이다.  

# Numpy

빠르고 쉽다!!   
★ 우리가 배울 모든 애들은 NumPy 기반으로 만들었다.  

파이썬 공식 built in이 아님으로 import 해야한다.

In [1]:
import numpy as np

In [34]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',


수학 함수가 굉장히 많음  
대문자가 먼저 나옴. dir 과 __dir 차이가 정렬임    
대문자 65 소문자 97 임으로 dir하면 대문자 먼저 나옴  
파이썬은 명시적인 상수가 없음(재할당 할 수 없음)  
대문자로 이루어져있으면 상수로 사용한다.  
파이썬은 순수한 객체지향 언어임으로 인스턴스, 리터럴 사용하는 방법을 이용한다.  
클래스를 이용해서 인스턴스하지 않고 다른함수의 힘을 이용하여 인스턴스화 하는 것을 팩토리 메소드라고 한다.  
numpy는 팩토리 메소드가 많다. (ex. np.array )  
파이썬 공식 라이브러리에도 array가 있음 (import array)  
array는 호모지니어스한 데이터타입이라고 한다.   
호모지니어스의 장점 -> 다음 데이터 타입이 뭐가 올 지 체크 할 필요가 없음 -> 속도가 빠르다.  

근데 파이썬 array는 잘 안쓴다.

In [6]:
a = np.array(1)

#np.array의 order는 c하고 포트넘 방식으로 할 수 있음.
#포트넘 메모리상에 일렬로 제장
# array_like : 호모지니어스 ,데이터가 하나 이상.

In [7]:
a

array(1)

In [26]:
a = np.array([1,2])

In [27]:
a

array([1, 2])

In [10]:
a = np.array((1,2))

In [11]:
a
# 튜플로 했는데 list로 바꿔준다.
# mutable
# copy 개념을 알아야한다.
# outpuat에 array가 붙어있으면 numpy이다.

array([1, 2])

In [13]:
type(a)
#ndarray -> nd는 n차원이라는 뜻

numpy.ndarray

In [15]:
#매트릭스 만드는 방법 (2차원)
a = np.array([[1,2],[3,4]])

In [16]:
a

array([[1, 2],
       [3, 4]])

In [19]:
#3차원은 공백이 있음
a = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [21]:
a
# 이렇게 무한 차원까지 늘릴 수 있다.

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [22]:
# 클래스를 인스턴스 하면 된다.
n = np.ndarray(0)

In [23]:
n
#결과가 미묘하게 다르다.
#dtpye이생김 → 호모지니어스인데 데이터타입이 중요할까?

array([], dtype=float64)

In [28]:
a = np.array(['1',2,3])
#np.array는 함수적인 역할을 함. 알아서 바꿔줌

In [29]:
a
#호모 지니어스한 타입으로 어떤 데이터 타입으로 다 바꾸어준다.
#팩토리 메소드 임으로 다른 데이터형태도 똑같은 데이터형태로 바꾸어준다.
# < 리틀인디언, > 빅인디언

array(['1', '2', '3'], dtype='<U1')

In [30]:
n = np.ndarray([0,'1'])
#error 발생
#호모지니어스한 데이터가 아니여서
#np.ndarray는 클래스적인 역할을 함

TypeError: 'str' object cannot be interpreted as an integer

In [33]:
# numpy는 자체적으로 쉽게 c에서 할 수 있는 수치해석을 쉽게 할 수 있다.
# dir 쓸 수 있는 모든 어트리뷰트를 알 수 있음
# vars 인스턴스 변수가 가진 애를 알 수 있음

1

In [35]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [36]:
vars(a)
# __dict__가 정의가 안되어있으면 vars 오류남
# 값을 1개만 가진다.

TypeError: vars() argument must have __dict__ attribute

In [41]:
a = np.array([[1,2],[3,4]])

In [42]:
a

array([[1, 2],
       [3, 4]])

In [39]:
a.ndim
# 차원을 알 수 있는 명령어.

2

In [40]:
len(a)

2

In [44]:
a.shape
#2행 2열
#행렬연산할 때 모양을 맞추기 위해서 중요하다.

(2, 2)

In [46]:
a.flags
# c방식으로 저장되어있고 f방식으로 저장되어 있지 않음.  
# c는 메모리상에 1,2,3,4 (옆으로 저장된다.)  
# f는 메모리상에 1,3,2,4로 저장된다.  

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [47]:
a.size
#원소의 갯수

4

In [50]:
a.itemsize
#하나의 원소가 몇 비트인가. 모염ㄴ어ㅏㅁ누아ㅓㅜㅁ너ㅏ움낭

4

In [59]:
x = [1,2,3,4]
y=  [2,3,4,5]

In [60]:
x+y
# 리스트 뒤에 추가 된다

[1, 2, 3, 4, 2, 3, 4, 5]

In [61]:
a = np.array([[1,2],[3,4]])
b=  np.array([[2,3],[4,5]])

In [62]:
a+b
#각각의 원소를 더해준다.

array([[3, 5],
       [7, 9]])

In [63]:
[a+b for a,b in zip(x,y)]
# x,y리스트로 array 덧셈하기

[3, 5, 7, 9]

In [64]:
a-b

array([[-1, -1],
       [-1, -1]])

In [65]:
a*b

array([[ 2,  6],
       [12, 20]])

이렇게 계산하는 방식을 elementwise방식  
복잡한 방법 없이 쉽게 계산할 수 있다.

In [66]:
a.T
#행과 열을 바꿔준다. 

array([[1, 3],
       [2, 4]])

# Scipy

분야별로 사람들이 많이 계산한 것 → 특히 과학   
이러한 것들을 numpy 기반으로 만들어 놓은 것    

linkedlist  
타입이 없고 메모리가 일렬로 저장되어있지 않음  

# Ndarray

몇번 째 무엇을 찾는가가 굉장히 중요하다.  
header에 datatype이 저장되어있음  
내부구조는 일렬임(c나 f나) strides라는 개념을 통해서 사람들 한테 보여줄 때 행렬처럼 보여줌(12바이트씩 요소당 4바이트 즉 3행 3열)  

파이썬에서  
_ ← private으로 사용함(단, from * 썼을때 _ 붙어있는애 import 되지 않음)   
__ ← OOP dir할 때 안나옴, 이름이 맹글링됨  
__ __ ← 매직메소드, 스페셜 메소드  

언더바가 맨 마지막 결과를 나눌 때 도 있다.  
_(a) ← 다국어 처리 할 때 사용  
이름_ ← 파이썬 키워드하고 똑같을 때 이름 충돌을 피하기 위해서 사용

In [71]:
a = np.array([[1,2],[3,4]], dtype ='u1')
# dtype ='u1' 타입코드 
# 쉽게 타입을 정의 할 수 있다.

In [72]:
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [73]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint32,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float64,
 'g': numpy.float64,
 13: numpy.float64,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,
 'c

In [74]:
len(np.sctypeDict)
# numpy 버전이 32bit이냐 64bit이냐에 따라서 다르다.
# 152개의 데이터타입을 지원해준다.

152

In [75]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


가장 큰 int64, float64, 128 말고는 사용하지 않는다.  
빅데이터를 다루기 때문에 작은 데이터 타입은 필요하지 않다.   

# Stride

In [70]:
a.strides
#최대공약수로 나눔
#2행 2열

(8, 4)

jump를 한번만 하면 모든 요소에 접근할 수 있다.  
벡터라이즈(벡터화)는 계산을 한번에 동시에 하는 것이기 때문에   

stride를 알고 있기 때문에 행렬을 flat으로 바꿔도 상관 없다.

32 bit -> 4byte  
16 bit -> 2byte  

바이트를 곱해준다.  
차원이 중요하지 않을 때는 stride 개념이 숨어 있다. 

stride가 c로 저장되어있을때랑 포트란 방식으로 저장되어있을 때와 다르다.  
c(행,열)  f(열,행)  

asis = 1 행 →  
asis = 0 열 ↓  

# arrange

numpy에서 range와 똑같은 역할을 한다.

In [83]:
a =np.arange(10)

In [84]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
b = a.reshape(2,5)
# 2행 5열로 바꾸어 진다.
# copy 개념이라서 재할당 필요하다.

In [89]:
a
#mutable(가변)이면 a.reshape하면 바뀌어야하는데 결과는 바뀌지 않음.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
#파이썬과 numpy하고 1대1 매칭이 됨 
#합구하는 함수 sum
b.sum()
# 전체합

45

In [102]:
b.sum(axis=1)
#(2,5)에서 1번째를 가리면 2개

array([10, 35])

In [105]:
b.sum(axis=0)
#(2,5)에서 0번째를 가리면 5개

array([ 5,  7,  9, 11, 13])

In [103]:
b.min()

0

In [106]:
%time sum(range(1000000))

Wall time: 6 ms


4999950000

In [107]:
%time np.sum(np.arange(1000000))
#np.arange가 상당히 빠르다는 걸 알 수 있다.
#numpy를 이용해서 코딩하면 자동으로 최적화가 된다.

Wall time: 2 ms


704982704

In [111]:
a =np.zeros((3,4))
# 0으로 튜플만들기

In [112]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [114]:
a = np.ones((3,4))
# 1로 튜플만들기

In [116]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [117]:
c = np.full((3,4),3)
# 원하는 숫자가 채워진 행렬만들기

In [118]:
c

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

zeros_like
ones_like 

In [119]:
d = np.ones_like(a)

In [120]:
d
#shpe만 가지고 와서 1로 만들어 준다.
#행렬연산할때 크기가 같아야함으로 크기를 맞출때 like를 자주 쓴다.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 단위행렬

In [ ]:
b= np.eye()
# 단위 행렬은 정방행렬만 단위 행렬 임으로 shape이 아니다.

In [121]:
b = np.eye(3)

In [122]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
c = np.identity(4)
#eye가 조금더 옵션이 많음.
#둘다 단위행렬을 만들때 사용한다.

In [126]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

대각 행렬, 삼사각행렬 등 이름이 있는 행렬을 다 만들 수 있다.

In [130]:
# 전치행렬
np.transpose(b)

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

# linspace

range와 비슷하지만 잘라서 사용할 수 있다.

In [133]:
d = np.linspace(0,99)

In [134]:
d

array([ 0.        ,  2.02040816,  4.04081633,  6.06122449,  8.08163265,
       10.10204082, 12.12244898, 14.14285714, 16.16326531, 18.18367347,
       20.20408163, 22.2244898 , 24.24489796, 26.26530612, 28.28571429,
       30.30612245, 32.32653061, 34.34693878, 36.36734694, 38.3877551 ,
       40.40816327, 42.42857143, 44.44897959, 46.46938776, 48.48979592,
       50.51020408, 52.53061224, 54.55102041, 56.57142857, 58.59183673,
       60.6122449 , 62.63265306, 64.65306122, 66.67346939, 68.69387755,
       70.71428571, 72.73469388, 74.75510204, 76.7755102 , 78.79591837,
       80.81632653, 82.83673469, 84.85714286, 86.87755102, 88.89795918,
       90.91836735, 92.93877551, 94.95918367, 96.97959184, 99.        ])

# logspace

In [135]:
e = np.logspace(1,100)

In [136]:
e

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

# empty

c에서 선언하면 쓰레기 값이 들어감   
empty도 마찬가지 초기화되지않은 값이 들어감  

In [137]:
e = np.empty((4,2))

In [138]:
e

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 5.65211099e-321],
       [2.13622844e-306, 2.00008875e+174]])

# 이제 만들어진 행렬에서 뽑아 내보자! 

인덱스, 슬라이스 : 시퀀스 타입  
numy는 순서가 중요함!! → 인덱싱이 된다.  
인덱싱 방식이 조금 확장 되어 있다.  

In [139]:
a = np.arange(10).reshape(2,5)

In [140]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

파이썬에서 8을 뽑아 내기 위한 방법

In [143]:
a[1][3]

8

numpy에서 8을 뽑아내는 방법

In [145]:
a[1,3]
# , 사용 파이썬에서는 사용 할 수 없다.

8

In [149]:
a[:,3]

array([3, 8])

In [151]:
a = np.arange(27).reshape(3,3,3)

In [152]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [159]:
a[1,:]
#a[1,:,:]과 같다

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [164]:
a[1,1,0]

12

In [160]:
a[1,...]
#...은 전부다 라는 뜻

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [162]:
# 인덱싱과 슬라이싱이 확장 되어서 사용된다.

In [172]:
a = np.arange(10)

In [168]:
a [(a>3) | (a<8)]
# 조건을 이용할 수 있다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
a[[True,False,True,True,True,True,True,True,True,True]]
#True인 애만 뽑아 내는 것
#마스킹 기법

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

# Fancy Indexing

꺽쇠가 두개임, 열뽑을 때 사용한다.  
a[[1,2]]  → 1행과 2행이 뽑힌다.  
a[[-1,-2]] → 뒤에서 1행과 2행

In [178]:
a =np.arange(10).reshape(5,2)

In [179]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [180]:
a[[1,3]]
#행을 예쁘게 뽑아준다.
#, ... 조건 마스킹 펜시 (5가지 방법)

array([[2, 3],
       [6, 7]])

In [181]:
#다양한 방법으로 인덱싱, 슬라이싱이 가능하다.

In [189]:
a[0]
#생략되면 전부다 가져옴

array([0, 1])

In [191]:
b =np.nditer(a)

In [193]:
next(b)
#단 for을 사용하면 안된다.

array(0)

In [194]:
def add_(a,b):
    return a+b

In [195]:
x = np.arange(5)
y= np.arange(5)

In [196]:
add_(x,y)

array([0, 2, 4, 6, 8])

In [197]:
x*3

array([ 0,  3,  6,  9, 12])

In [198]:
3 + np.arange(10)
#크기를 알아서 맞춰줌 broadcasting

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# nfunc

범용적으로 사용할 수 있는 함수

In [200]:
abs(-1)

1

In [201]:
abs([-1,1,2])
#error 발생

TypeError: bad operand type for abs(): 'list'

In [202]:
np.abs([-1,1,2])

array([1, 1, 2])

In [204]:
np.ceil([2.9,1,2,3,0.3])

array([3., 1., 2., 3., 1.])

파이썬에 있는 함수는 대부분 있다고 생각하면 된다.

In [205]:
# *키워드 온리 / 포지셔널 온리

In [208]:
! pip install scipy

You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [210]:
from scipy.special import factorial

In [212]:
factorial([3,4,5])

array([  6.,  24., 120.])

In [213]:
np.info(factorial)
# scipy도 numpy로 만들어서 numpy 에러로 나온다.

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


정말 많은 ufuns들이 있다.

np.where 조건을 쓸 때 사용한다.

In [216]:
b =np.arange(10)

In [218]:
np.where(b>5,0,1)
#5보다 크면 0으로 아니면 1로 바꿔라.
#if else구문과 같이 사용할 수 있다.
#그냥 쓰면 조건에 해당하는 인덱스를 알려준다.

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [219]:
b[np.where(b>5)]
#Np.where은 조건문 뿐만아니라 변화시키는 기능도 한다.

array([6, 7, 8, 9])

In [257]:
a = np.arange(10).reshape(2,5)

In [258]:
b = a
# 그냥할당임으로 당연히 바뀌어야함.

In [259]:
b[0][0] = 200

In [260]:
a

array([[200,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [261]:
b

array([[200,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [229]:
c = b.copy()
#파이썬에서 copy는 스왈로copy

In [230]:
c
# numpy에서는 deep copy이다. 
# 파이썬하고 반대
# numpy는 기본적으로 다 중첩시킴으로

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [248]:
# 스왈로 카피는 view이용
d = b.view()

In [250]:
d[0][0] = 700

In [246]:
b
# b를 d에다가 스왈로 copy 하고
# d[0][0]에 700을 넣으면 d는 바뀌고 b는 안바뀜

array([[600,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [251]:
d

array([[700,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])